[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "openssl"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm ci --ignore-scripts",
  "pip install -r requirements.txt"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npx prisma generate",
  "npx prisma db push --accept-data-loss",
  "next build"
]

[start]
cmd = "npx prisma db push --accept-data-loss && next start -p ${PORT:-3000}"
