[build]
builder = "NIXPACKS"
buildCommand = "npm install && prisma generate && next build"

[deploy]
startCommand = "prisma migrate deploy && next start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
