[build]
builder = "NIXPACKS"
buildCommand = "npm install && prisma generate && next build"

[deploy]
startCommand = "prisma migrate deploy; next start -p ${PORT:-3000}"
healthcheckPath = "/login"
restartPolicyType = "ON_FAILURE"
